### ISSUE TITLE
Default order state "Shipped" instead of "Payment accepted"

### ISSUE THREAD

**Issue by 8191** [paylike/plugin-thirtybees#9]
A new order is created as "Shipped", as the default order status list for ThirtyBees maps ID 3 to "Shipped":

https://github.com/paylike/plugin-thirtybees/blob/1da87afd05469fdfdaa6898d7932f286bb77d8d3/paylikepayment/controllers/front/paymentreturn.php#L104

This value needs to be configurable.

**Comment by ionutcalara** [comment]
Thank you for mentioning this, we'll look into changing this in our next release.

**Comment by ionutcalara** [comment]
@8191 the latest release 1.1.0, made this configurable. Thank you for the report, I will close this for now, but if you need to reopen, feel free to do so.
